name: Function Deployment
env:
  appName: ${{ vars.APP_PREFIX }}-cosu-fn
  appPath: ./src/ContosoSuitesVectorizationFunction
on:
  push:
    branches: [ main ]
    paths: src/ContosoSuitesVectorizationFunction/**
  pull_request:
    branches: [ main ]
    paths: src/ContosoSuitesVectorizationFunction/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      publishPath: ${{ steps.publish.outputs.publishPath }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    - name: Restore dependencies
      run: dotnet restore $appPath

    - name: Build
      run: dotnet build --configuration Release --no-restore $appPath

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish $appPath 

    - name: Login via Azure CLI
      uses: azure/login@v2.1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: ${{ env.appName }}
        package: ./publish